// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqrnvllzfdkspjfwmng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcXJudmxsemZka3NwamZ3bW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTA4ODEsImV4cCI6MjA3MDU4Njg4MX0.MLUOIK8_4iI0BpamuKQ0MWQY2YOd86lynHhGpZHITIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});